function mds_ds = mk_ccle_rna_seq_mds_function(varargin)
%Runs tsne on the ccle rnaseq data set and writes an annotated text file
%which can be passed to tableau.

params = {'metric',...
    'normalize',...
    'num_pcs',...
    'write_text_file',...
    'outdir'};
dflts = {'euclidean',...
    1,...
    10,...
    false,...
    '/cmap/projects/cell_line_diversity/analysis/ccle_rna_seq_viz/tsne/'};
args = parse_args(params,dflts,varargin{:});

ccle_pdist = compute_genex_sim('metric',args.metric,...
    'norm',args.normalize,...
    'num_pcs',args.num_pcs);

%%Run MDS
mds = cmdscale(double(ccle_pdist.mat),2);
mds_ds = mkgctstruct(mds,'rid',ccle_pdist.rid,'cid',{'MDS1','MDS2'});
annot = meta2struct(ccle_pdist,'dim','row');
mds_ds = annotate_ds(mds_ds,annot,'dim','row');

figure;
scatter(mds(:,1),mds(:,2))

%Tableauify
temp1 = table(mds_ds.mat(:,1),mds_ds.mat(:,2),mds_ds.rid,...
    'VariableNames',{'MDS_1','MDS_2','cell_name'});
temp2 = cell2table(mds_ds.rdesc,'VariableNames',mds_ds.rhd);
tsne_table = [temp1 temp2];

%Write table
if args.write_text_file
    outfile = sprintf('ccle_rnaseq_mds_%s_norm_%d_num_pcs_%d',...
        args.metric,...
        args.normalize,...
        args.num_pcs);

    writetable(tsne_table,fullfile(args.outdir,outfile),...
        'FileType','text',...
        'Delimiter','\t');
end
end