cn = parse_gctx('/cmap/data/vdb/cline/ccle_copynumber_bygene_20120929_n899x11774.gctx');

% Plot histogram of gene cn variance
figure;
gene_vars = mkgctstruct(var(cn.mat,[],2),...
    'rid',cn.rid,...
    'cid',{'copy_number_variance'});
[~,idx] = sort(gene_vars.mat,1,'descend');
temp = gene_vars.rid(idx);
most_variable_genes = temp(1:100);
histogram(gene_vars.mat)
xlabel('Variance across samples')
ylabel('Count')
title('Variance of per gene copy number across samples')

% Plot histogram of sample cn variance
figure;
sample_vars = var(cn.mat);
histogram(sample_vars)
xlabel('Variance across genes')
ylabel('Count')
title('Variance of per sample copy number across genes')

%pca
sig_pca_tool('--ds',cn,...
    '--dim','row',...
    '--row_space',most_variable_genes,...
    '--create_subdir',0,...
    '-o','/cmap/projects/cell_line_diversity/analysis/scratch',...
    'rpt','ccle_cn')

%tsne
sig_tsne_tool('--ds',cn,...
    '--create_subdir',0,...
    '--rid',most_variable_genes,...
    '-o','/cmap/projects/cell_line_diversity/analysis/scratch',...
    'rpt','ccle_cn_tsne',...
    'initial_dim',30,...
    'perplexity',30)