%Make ccle RNA-Seq PCA. Annotate. Tableauify

sig_pca_tool('--ds','/cmap/projects/cell_line_diversity/data/CCLE_BASELINE_RNASEQ_L1KFULL_RPKM_LOG2_n1022x12450.gctx',...
    '--dim','row',...
    '--create_subdir',0,...
    '--out','/cmap/projects/cell_line_diversity/analysis/ccle_rna_seq_viz/pca')

% tableaufiy
pca_ds = parse_gctx('/cmap/projects/cell_line_diversity/analysis/ccle_rna_seq_viz/pca/pc_score_n1021x1022.gctx');
temp1 = table(pca_ds.mat(:,1),pca_ds.mat(:,2),...
    'VariableNames',{'PCA_1','PCA_2'});
temp2 = cell2table(pca_ds.rdesc,'VariableNames',pca_ds.rhd);
pca_table = [temp1 temp2];

writetable(pca_table,'/cmap/projects/cell_line_diversity/analysis/ccle_rna_seq_viz/pca/ccle_rnaseq_pca_annotated.txt',...
    'FileType','text',...
    'Delimiter','\t');